name: Atualizar lista de países

on:
  schedule:
    - cron: "0 * * * *"   # a cada hora
  workflow_dispatch:

jobs:
  sync-countries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Sincronizar lista de países nos ficheiros JS
        run: node js/sync-paises.js

      - name: Corrigir países nos ficheiros JSON em Tables
        run: node js/sync-countries-in-tables.js

      - name: Commit e push se houver alterações
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add js/mapas/mapa-controller.js js/paises.js Tables/*.json
          git diff --cached --quiet || git commit -m "Sincronização automática de países"
          git push
