name: Atualizar lista de tabelas

on:
  schedule:
    - cron: "0 * * * *"   # a cada hora
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Gerar tables-list.json
        run: node js/admin/generate-tables-list.js

      - name: Commit e push se houver alterações
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add Tables/tables-list.json
          git diff --cached --quiet || git commit -m "Atualizar tables-list.json automaticamente"
          git push
